// Simple language switcher for English/French
// Usage: add data-i18n="key" to elements whose text should be translated
//        add data-i18n-placeholder="key" to inputs for their placeholder
//        add data-i18n-title="key" for title attributes
// The toggle button should have id="toggleLang" and a span with id="langLabel" to display current code.

const translations = {
    fr: {
        dashboard: 'Tableau de Bord',
        sensitive_ops: 'Opérations Sensibles',
        messaging: 'Messagerie',
        settings: 'Paramètres',
        logout: 'Déconnexion',
        global_stats: 'Statistiques Globales',
        companies: 'Compagnies',
        invoices: 'Factures',
        disputes: 'Contestations',
        validated: 'Validées',
        account_settings: "Configuration du Compte",
        search_company: 'Rechercher la compagnie...',
        select_company: 'Sélectionnez une compagnie',
        recent_messages: 'Messages récents',
        select_company_view: 'Sélectionnez une compagnie pour voir les messages ici.',
        no_operations: 'Aucune opération trouvée',
        prev: 'Préc',
        next: 'Suiv',
        page: 'Page',
        items: 'éléments',
        validate: 'Valider',
        reject: 'Rejeter',
        ops_sub: 'Liste, filtrage et gestion des opérations à risque',
        mode: 'Mode',
        not_connected: 'Vous n\'êtes pas connecté !',
        session_expired: 'Session expirée. Veuillez vous reconnecter.',
        upload_proof: 'Téléverser une preuve',
        submit_dispute: 'Soumettre une contestation',
        my_account: 'Mon Compte',
        client_dashboard: 'Tableau de bord Client',
        invoice_concerned: 'Facture concernée',
        detailed_explanation: 'Explication Détaillée',
        upload_evidence: 'Téléverser des preuves',
        or_drag_drop: 'ou glissez-déposez',
        file_types: 'PDF, PNG, JPG (MAX. 5 fichiers)',
        submit_dispute_button: 'Soumettre la Contestation',
        upload_confirmation: 'Confirmer & téléverser',
        search_invoice: 'Rechercher une facture...',
        download_csv: 'Télécharger récap (.CSV)',
        operation_success: 'Opération Réussie',
        operation_message: 'Votre action a été traitée avec succès.',
        notifications: 'Notifications',
        valid_invoices: 'Factures valides',
        total_invoices: 'Factures totales',
        dispute_invoices: 'Factures contestées',
        invoice_number: 'N° facture',
        issue_date: 'Date émise',
        amount: 'Montant',
        status: 'Statut',
        action: 'Action',
        view: 'Voir',
        close: 'Fermer',
        supporting_documents_optional: 'Documents Justificatifs (Optionnel)',
        page_title_submit_dispute: 'ASSA-AC Portail Client - Soumettre Contestation',
        page_title_account_settings: 'ASSA-AC Portail Client - Mon Compte',
        page_title_upload_proof: 'ASSA-AC Portail Client - Téléverser Preuve',
        page_title_messaging: 'ASSA-AC Portail Client - Messagerie',
        language: 'Langue',
        televerser: 'Téléverser',
        contestation: 'Contestation',
        messagerie: 'Messagerie',
        contact_billing_info: 'Informations de Contact et Facturation',
        logo_file_types: 'JPG, PNG ou SVG (max. 1MB)',
        choose_logo: 'Choisir le logo',
        save: 'Enregistrer',
        company_name_label: 'Nom de la compagnie',
        client_number_label: 'Numéro Client ASSA-AC',
        contact_email_label: 'Email de Contact',
        phone_label: 'Téléphone',
        headquarters_address_label: 'Adresse du Siège',
        save_information: 'Sauvegarder les Informations',
        security: 'Sécurité',
        current_password: 'Mot de passe actuel',
        new_password: 'Nouveau mot de passe',
        upload_payment_proof: 'Téléverser Preuve de Paiement',
        payment_proof_label: 'Preuve de Paiement',
        file_types_single: 'PDF, PNG, JPG (MAX. 1 fichier)',
        support_title: 'Support ASSA-AC',
        online: 'En ligne',
        validate: 'Valider',
        id_setup_instruction: 'Renseignez au moins company_id pour recevoir les messages en direct.',
        write_your_message: 'Écrivez votre message...',
        attach_file: 'Joindre un fichier',
        files_to_send: 'Fichiers à envoyer :',
        company_id_placeholder: 'company_id (UUID)',
        admin_id_placeholder: 'admin_id (optionnel)',
        // Admin pages
        active_companies: 'Compagnies Actives',
        total_number_invoices: 'Nombre total de factures',
        disputed_invoices: 'Factures Contestées',
        needs_action: 'Nécessite une action rapide',
        new_invoice: 'Nouvelle Facture',
        create: 'Créer',
        quick_access: 'Accès rapide',
        recent_activity: 'Journal d\'Activité Récent',
        activity_type: 'Type d\'Activité',
        description: 'Description',
        user: 'Utilisateur',
        manage_companies: 'Gestion des Compagnies',
        refresh: 'Actualiser',
        add_company: 'Ajouter Compagnie',
        search_company_id: 'Rechercher une compagnie, un ID...',
        operation_log: 'Journal d\'Activité',
        search_action_user: 'Rechercher une action ou un utilisateur...',
        filter_user: 'Utilisateur',
        filter_action: 'Type d\'Action',
        filter_date: 'Date',
        all: 'Tous',
        all_types: 'Tous les types',
        create_action: 'Création (Facture/Devis)',
        update_action: 'Modification (Compagnie/Statut)',
        delete_action: 'Archivage/Suppression',
        system_action: 'Connexion/Système',
        refresh_button: 'Actualiser',
        invoicing: 'Facturation',
        search_invoice_company_date: 'Rechercher par Compagnie, Date ou N° Facture...',
        invoice_management: 'Gestion des factures',
        consult_filter_export: 'Consultez, filtrez et exportez vos factures',
        create_invoice: 'Créer Facture',
        export: 'Exporter',
        filter: 'Filtrer',
        by_month: 'Par mois',
        dec_2025: 'Décembre 2025',
        nov_2025: 'Novembre 2025',
        oct_2025: 'Octobre 2025',
        all_companies: 'Toutes compagnies',
        by_status: 'Par statut',
        paid: 'Payée',
        unpaid: 'Impayée',
        disputed: 'Contestée',
        invoices_list: 'Liste des Factures',
        emission_date: 'Date d\'Émission',
        general: 'Général',
        themes_appearance: 'Thèmes & Apparence',
        general_info: 'Informations Générales de la Société',
        company_name_field: 'Nom de la Société',
        headquarters_address_field: 'Adresse du Siège Social',
        official_email_field: 'E-mail Officiel',
        save_general_settings: 'Sauvegarder les Paramètres Généraux',
        themes_mode_desc: 'Thèmes et Mode d\'Affichage',
        select_theme: 'Sélectionnez un Thème (Persistant)',
        your_choice_saved: 'Votre choix sera sauvegardé et appliqué à toutes les pages de l\'application (grâce à `localStorage`).',
        light_mode: 'Mode Jour',
        dark_mode: 'Mode Nuit',
        automatic: 'Automatique',
        account_security: 'Sécurité du Compte',
        change_password: 'Modifier le Mot de Passe',
        current_password_field: 'Mot de Passe Actuel',
        new_password_field: 'Nouveau Mot de Passe',
        confirm_password: 'Confirmer le Nouveau Mot de Passe',
        update_password_button: 'Mettre à Jour le Mot de Passe',
        two_factor_auth: 'Authentification à Deux Facteurs (2FA)',
        two_factor_desc: 'Renforcez la sécurité de votre compte en activant la vérification en deux étapes.',
        registry_operations: 'Régistre des opérations',
        archive_report: 'Rapport d\'Archive',
        current_month: 'Mois en cours',
        last_month: 'Mois dernier',
        download_summary: 'Télécharger le Récapitulatif (.CSV)',
        closed_docs: 'Factures et Documents Clôturés',
        type_col: 'Type',
        ref_col: 'N° Réf.',
        amount_col: 'Montant (XAF)',
        actions_col: 'Actions',
        archive_details: 'Détails de l\'archive',
        agent_col: 'Agent',
        // Invoice management messages
        session_expired_redirect: 'Votre session a expiré. Veuillez vous reconnecter.',
        error_loading_invoices: 'Erreur chargement factures',
        unable_load_invoices: 'Impossible de charger les factures.',
        confirm_invoice_paid: 'Confirmer cette facture comme payée ?',
        invoice_confirmed: 'Facture confirmée !',
        api_error: 'Erreur API',
        no_invoices_export: 'Aucune facture à exporter.',
        confirm_delete_invoice: 'Supprimer définitivement cette facture ?',
        invoice_removed: 'Facture retirée !',
        error_deletion: 'Erreur lors de la suppression.',
        unable_open_proof: 'Impossible d\'ouvrir la preuve.',
        no_proof_uploaded: 'Aucune preuve (paiement ou contestation) n\'a été téléversée pour cette facture.',
        dispute_no_file: 'La contestation n\'a pas de fichier joint.',
        error_confirmation: 'Erreur confirmation:',
        json_response_error: 'Réponse non JSON reçue :',
        // Sidebar navigation
        representative: 'Représentant',
        email: 'E-mail',
        phone: 'Téléphone',
        address: 'Adresse',
        airport_code: 'Code Aéroport',
        active: 'Actif',
        // Activity log
        module: 'Module',
        authentication: 'Authentification',
        connection: 'Connexion',
        company_connection: 'Connexion de la compagnie',
        invoice_creation: 'Création de la facture',
        company_updated: 'mise à jour',
        // Invoice form
        invoice_data_entry: 'SAISIE DES DONNÉES DE FACTURE',
        invoice_references: 'Références de la Facture',
        issued_at: 'Fait à',
        ex_city: 'Ex: Pointe-Noire',
        airport: 'Aéroport',
        ex_airport: 'Ex: Aéroport International Malabo',
        duty_articles: 'Articles de Redevance',
        number: 'N°',
        designation: 'Désignation',
        passengers_flights: 'Nbre Passagers / Vols',
        zone: 'Zone',
        choose_zone: 'Choisir la Zone',
        total_cost: 'Coût Total (Frs)',
        delete: 'Suppr.',
        total: 'TOTAL',
        xaf_currency: 'Frs CFA',
        invoice_totaled: 'Arrêtée la présente facture à la somme de',
        zero: 'ZÉRO',
        invoice_preview: 'Aperçu de la Facture'
    },
    en: {
        dashboard: 'Dashboard',
        sensitive_ops: 'Sensitive Ops',
        modal_info: 'Info',
        modal_message: 'Message...',
        page_title_upload_proof: 'ASSA-AC Client Portal - Upload Proof',
        page_title_messaging: 'ASSA-AC Client Portal - Messaging',
        televerser: 'Upload',
        messaging: 'Messaging',
        settings: 'Settings',
        logout: 'Logout',
        global_stats: 'Global Statistics',
        companies: 'Companies',
        invoices: 'Invoices',
        disputes: 'Disputes',
        validated: 'Validated',
        account_settings: 'Account Settings',
        search_company: 'Search company...',
        select_company: 'Select a company',
        recent_messages: 'Recent messages',
        select_company_view: 'Select a company to view messages here.',
        no_operations: 'No operations found',
        prev: 'Prev',
        next: 'Next',
        page: 'Page',
        items: 'items',
        validate: 'Validate',
        reject: 'Reject',
        ops_sub: 'List, filter and manage high‑risk operations',
        table_ops_caption: 'Table of sensitive operations',
        mode: 'Mode',
        not_connected: 'You are not logged in!',
        session_expired: 'Session expired. Please log in again.',
        upload_proof: 'Upload Proof',
        payment_proof_label: 'Payment Proof',
        file_types_single: 'PDF, PNG, JPG (MAX. 1 file)',
        support_title: 'ASSA-AC Support',
        online: 'Online',
        validate: 'Validate',
        id_setup_instruction: 'Enter at least company_id to receive live messages.',
        write_your_message: 'Write your message...',
        attach_file: 'Attach file',
        files_to_send: 'Files to send:',
        company_id_placeholder: 'company_id (UUID)',
        admin_id_placeholder: 'admin_id (optional)',
        submit_dispute: 'Submit Dispute',
        my_account: 'My Account',
        client_dashboard: 'Client Dashboard',
        invoice_concerned: 'Invoice',
        detailed_explanation: 'Detailed Explanation',
        upload_evidence: 'Upload Evidence',
        or_drag_drop: 'or drag & drop',
        file_types: 'PDF, PNG, JPG',
        submit_dispute_button: 'Submit Dispute',
        upload_confirmation: 'Confirm & Upload',
        search_invoice: 'Search invoice...',
        download_csv: 'Download Recap (.CSV)',
        operation_success: 'Operation Successful',
        operation_message: 'Your action was successful.',
        notifications: 'Notifications',
        valid_invoices: 'Valid Invoices',
        total_invoices: 'Total Invoices',
        dispute_invoices: 'Disputed Invoices',
        invoice_number: 'Invoice No.',
        issue_date: 'Issue Date',
        amount: 'Amount',
        status: 'Status',
        action: 'Action',
        view: 'View',
        language: 'Language',
        close: 'Close',
        supporting_documents_optional: 'Supporting Documents (Optional)',
        page_title_submit_dispute: 'ASSA-AC Client Portal - Submit Dispute',
        page_title_account_settings: 'ASSA-AC Client Portal - Account Settings',
        page_title_upload_proof: 'ASSA-AC Client Portal - Upload Proof',
        televerser: 'Upload',
        contestation: 'Disputes',
        messagerie: 'Messaging',
        contact_billing_info: 'Contact & Billing Info',
        logo_file_types: 'JPG, PNG or SVG (max 1MB)',
        choose_logo: 'Choose logo',
        save: 'Save',
        company_name_label: 'Company name',
        client_number_label: 'ASSA-AC Client Number',
        contact_email_label: 'Contact Email',
        phone_label: 'Phone',
        headquarters_address_label: 'Headquarters Address',
        save_information: 'Save Information',
        security: 'Security',
        current_password: 'Current password',
        new_password: 'New password',
        update_password: 'Update password',
        modal_info: 'Info',
        modal_message: 'Message...',
        // Admin pages
        active_companies: 'Active Companies',
        total_number_invoices: 'Total Number of Invoices',
        disputed_invoices: 'Disputed Invoices',
        needs_action: 'Requires quick action',
        new_invoice: 'New Invoice',
        create: 'Create',
        quick_access: 'Quick Access',
        recent_activity: 'Recent Activity Log',
        activity_type: 'Activity Type',
        description: 'Description',
        user: 'User',
        manage_companies: 'Company Management',
        refresh: 'Refresh',
        add_company: 'Add Company',
        search_company_id: 'Search a company, an ID...',
        operation_log: 'Activity Log',
        search_action_user: 'Search an action or a user...',
        filter_user: 'User',
        filter_action: 'Action Type',
        filter_date: 'Date',
        all: 'All',
        all_types: 'All types',
        create_action: 'Creation (Invoice/Quote)',
        update_action: 'Modification (Company/Status)',
        delete_action: 'Archiving/Deletion',
        system_action: 'Login/System',
        refresh_button: 'Refresh',
        invoicing: 'Invoicing',
        search_invoice_company_date: 'Search by Company, Date or Invoice No...',
        invoice_management: 'Invoice Management',
        consult_filter_export: 'View, filter and export your invoices',
        create_invoice: 'Create Invoice',
        export: 'Export',
        filter: 'Filter',
        by_month: 'By month',
        dec_2025: 'December 2025',
        nov_2025: 'November 2025',
        oct_2025: 'October 2025',
        all_companies: 'All companies',
        by_status: 'By status',
        paid: 'Paid',
        unpaid: 'Unpaid',
        disputed: 'Disputed',
        invoices_list: 'Invoice List',
        emission_date: 'Issue Date',
        general: 'General',
        themes_appearance: 'Themes & Appearance',
        general_info: 'Company General Information',
        company_name_field: 'Company Name',
        headquarters_address_field: 'Headquarters Address',
        official_email_field: 'Official Email',
        save_general_settings: 'Save General Settings',
        themes_mode_desc: 'Themes and Display Mode',
        select_theme: 'Select a Theme (Persistent)',
        your_choice_saved: 'Your choice will be saved and applied to all pages of the application (thanks to `localStorage`).',
        light_mode: 'Light Mode',
        dark_mode: 'Dark Mode',
        automatic: 'Automatic',
        account_security: 'Account Security',
        change_password: 'Change Password',
        current_password_field: 'Current Password',
        new_password_field: 'New Password',
        confirm_password: 'Confirm New Password',
        update_password_button: 'Update Password',
        two_factor_auth: 'Two-Factor Authentication (2FA)',
        two_factor_desc: 'Strengthen your account security by enabling two-step verification.',
        registry_operations: 'Operations Registry',
        archive_report: 'Archive Report',
        current_month: 'Current month',
        last_month: 'Last month',
        download_summary: 'Download Summary (.CSV)',
        closed_docs: 'Closed Invoices and Documents',
        type_col: 'Type',
        ref_col: 'Ref No.',
        amount_col: 'Amount (XAF)',
        actions_col: 'Actions',
        archive_details: 'Archive Details',
        agent_col: 'Agent',
        // Invoice management messages
        session_expired_redirect: 'Your session has expired. Please log in again.',
        error_loading_invoices: 'Error loading invoices',
        unable_load_invoices: 'Unable to load invoices.',
        confirm_invoice_paid: 'Confirm this invoice as paid?',
        invoice_confirmed: 'Invoice confirmed!',
        api_error: 'API Error',
        no_invoices_export: 'No invoices to export.',
        confirm_delete_invoice: 'Permanently delete this invoice?',
        invoice_removed: 'Invoice removed!',
        error_deletion: 'Error during deletion.',
        unable_open_proof: 'Unable to open proof.',
        no_proof_uploaded: 'No proof (payment or dispute) has been uploaded for this invoice.',
        dispute_no_file: 'The dispute has no attached file.',
        error_confirmation: 'Confirmation error:',
        json_response_error: 'Non-JSON response received:',
        // Sidebar navigation
        representative: 'Representative',
        email: 'Email',
        phone: 'Phone',
        address: 'Address',
        airport_code: 'Airport Code',
        active: 'Active',
        // Activity log
        module: 'Module',
        authentication: 'Authentication',
        connection: 'Connection',
        company_connection: 'Company connection',
        invoice_creation: 'Invoice creation',
        company_updated: 'updated',
        // Invoice form
        invoice_data_entry: 'INVOICE DATA ENTRY',
        invoice_references: 'Invoice References',
        issued_at: 'Issued at',
        ex_city: 'Ex: Pointe-Noire',
        airport: 'Airport',
        ex_airport: 'Ex: International Airport Malabo',
        duty_articles: 'Duty Articles',
        number: 'No.',
        designation: 'Designation',
        passengers_flights: 'Passengers/Flights',
        zone: 'Zone',
        choose_zone: 'Choose Zone',
        total_cost: 'Total Cost (Frs)',
        delete: 'Delete',
        total: 'TOTAL',
        xaf_currency: 'XAF',
        invoice_totaled: 'Invoice totaled to the sum of',
        zero: 'ZERO',
        invoice_preview: 'Invoice Preview'
    }
};

function applyLanguage(lang) {
    const dict = translations[lang] || translations.fr;
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (dict[key] !== undefined) {
            el.textContent = dict[key];
        }
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (dict[key] !== undefined) {
            el.placeholder = dict[key];
        }
    });
    document.querySelectorAll('[data-i18n-title]').forEach(el => {
        const key = el.getAttribute('data-i18n-title');
        if (dict[key] !== undefined) {
            el.title = dict[key];
        }
    });
    const label = document.getElementById('langLabel');
    if (label) {
        label.textContent = lang.toUpperCase();
    }
    // update html lang attribute for accessibility
    if (document.documentElement) {
        document.documentElement.lang = lang;
    }
}

// helper usable from other scripts
function t(key) {
    const lang = localStorage.getItem('lang') || 'fr';
    return (translations[lang] && translations[lang][key]) || translations.fr[key] || key;
}
window.t = t;

function setLanguage(lang) {
    localStorage.setItem('lang', lang);
    applyLanguage(lang);
}

function toggleLanguage() {
    const current = localStorage.getItem('lang') || 'fr';
    const next = current === 'fr' ? 'en' : 'fr';
    setLanguage(next);
}

document.addEventListener('DOMContentLoaded', () => {
    const lang = localStorage.getItem('lang') || 'fr';
    applyLanguage(lang);
    const btn = document.getElementById('toggleLang');
    if (btn) {
        btn.addEventListener('click', toggleLanguage);
    }
});

// expose for other scripts if needed
window.setLanguage = setLanguage;
window.toggleLanguage = toggleLanguage;